version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
        name: Install Package
        command: npm install


      - run:
        name: Build the Project
        command: npm run build

      - aws-s3/copy:
          from: ../build
          to: "s3://searchimage"
          aws-access-key-id: AKIAIPO47POA2CIWS5FA
          aws-secret-access-key: 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
          aws-region: us-east-1
          arguments: --dryrun

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test